### PR TITLE
Tables and Links

### PR DESCRIPTION
**Pull request by mhoffmeyerDC**
Howdy!

I didn't like that I couldn't click on any of the links to view the application's repo. So moving everything to a markdown table and adding hyperlinks.

This might not be desirable from a maintenance perspective, but I'll let you be the decider of that.

Thanks!

### CODE REVIEW

**Comment by whalehub** [comment]
@mhoffmeyerDC Thanks for the pull request, but it looks like the current implementation of this idea is broken. The hyperlinks are missing a protocol which results in all of them linking to a 404 page.

That being said, while I do prefer the format I have right now for the README itself, I'm not opposed to adding an optional table with easily accessible links to the repository.

**Comment by whalehub** [comment]
@mhoffmeyerDC I just implemented this suggestion in https://github.com/whalehub/ginstall.sh/commit/9d5f7792108adf67053bf1fadbdc9b925046c8d7. 👍

**Comment by mhoffmeyerDC** [comment]
See this is what happens when I don't go through QA! 

Thanks for taking a look and improving.

Cheers!

**Comment by whalehub** [comment]
@mhoffmeyerDC Just in case you're curious, I avoided creating an additional maintenance burden because of this change by piping the output from `ginstall.sh -l` through `sed`.

**Input**
```
Application:                Repository:
------------                -----------
A
acme-dns                    github.com/joohoi/acme-dns
adguardhome                 github.com/AdguardTeam/AdGuardHome
age                         github.com/FiloSottile/age
andesite                    github.com/nektro/andesite
annie                       github.com/iawia002/annie
apizza                      github.com/harrybrwn/apizza
arc                         github.com/mholt/archiver
argocd                      github.com/argoproj/argo-cd
authelia                    github.com/authelia/authelia
autocert                    github.com/smallstep/autocert

B
bed                         github.com/itchyny/bed
bin                         github.com/w4/bin
blocky                      github.com/0xERR0R/blocky
bombardier                  github.com/codesenberg/bombardier
brig                        github.com/sahib/brig
bw                          github.com/bitwarden/cli

C
caddy                       github.com/caddyserver/caddy
caire                       github.com/esimov/caire
captainhook                 github.com/bketelsen/captainhook
ccat                        github.com/jingweno/ccat
chroma                      github.com/alecthomas/chroma
cloud-torrent               github.com/jpillora/cloud-torrent
cobalt                      github.com/cobalt-org/cobalt.rs
comics-downloader           github.com/Girbons/comics-downloader
composer                    github.com/composer/composer
coredns                     github.com/coredns/coredns
croc                        github.com/schollz/croc
ctop                        github.com/bcicen/ctop

[...]
```

**Command**
```
sed "1,2d;/^$/d;s,^,| ,g;s,| [A-Z],,g;/^$/d;s,github.com,| https://github.com,g;s,$, |,g"'
```

**Output**
```
| acme-dns                    | https://github.com/joohoi/acme-dns |
| adguardhome                 | https://github.com/AdguardTeam/AdGuardHome |
| age                         | https://github.com/FiloSottile/age |
| andesite                    | https://github.com/nektro/andesite |
| annie                       | https://github.com/iawia002/annie |
| apizza                      | https://github.com/harrybrwn/apizza |
| arc                         | https://github.com/mholt/archiver |
| argocd                      | https://github.com/argoproj/argo-cd |
| authelia                    | https://github.com/authelia/authelia |
| autocert                    | https://github.com/smallstep/autocert |
| bed                         | https://github.com/itchyny/bed |
| bin                         | https://github.com/w4/bin |
| blocky                      | https://github.com/0xERR0R/blocky |
| bombardier                  | https://github.com/codesenberg/bombardier |
| brig                        | https://github.com/sahib/brig |
| bw                          | https://github.com/bitwarden/cli |
| caddy                       | https://github.com/caddyserver/caddy |
| caire                       | https://github.com/esimov/caire |
| captainhook                 | https://github.com/bketelsen/captainhook |
| ccat                        | https://github.com/jingweno/ccat |
| chroma                      | https://github.com/alecthomas/chroma |
| cloud-torrent               | https://github.com/jpillora/cloud-torrent |
| cobalt                      | https://github.com/cobalt-org/cobalt.rs |
| comics-downloader           | https://github.com/Girbons/comics-downloader |
| composer                    | https://github.com/composer/composer |
| coredns                     | https://github.com/coredns/coredns |
| croc                        | https://github.com/schollz/croc |
| ctop                        | https://github.com/bcicen/ctop |

[...]
```

**Comment by mhoffmeyerDC** [comment]
That is some regex/sed pipe thing! They're like the hieroglyphs of computer science.

Nice!

**Comment by whalehub** [comment]
@mhoffmeyerDC Haha, it honestly looks a lot more complicated than it is. I'll take it step-by-step.

***

**Command**
```
sed "1,2d;/^$/d;s,^,| ,g;s,| [A-Z],,g;/^$/d;s,github.com,| https://github.com,g;s,$, |,g"
```

**Input**
```
Application:                Repository:
------------                -----------
A
acme-dns                    github.com/joohoi/acme-dns
adguardhome                 github.com/AdguardTeam/AdGuardHome
age                         github.com/FiloSottile/age


B
bed                         github.com/itchyny/bed
bin                         github.com/w4/bin
blocky                      github.com/0xERR0R/blocky

C
caddy                       github.com/caddyserver/caddy
caire                       github.com/esimov/caire
captainhook                 github.com/bketelsen/captainhook
```

***

**Step #­1:** Delete the first two lines
```
1,2d;
```
`1,2` =select lines 1-2
`d` = delete
`;` = separator between `sed` steps

**Output**
```
A
acme-dns                    github.com/joohoi/acme-dns
adguardhome                 github.com/AdguardTeam/AdGuardHome
age                         github.com/FiloSottile/age


B
bed                         github.com/itchyny/bed
bin                         github.com/w4/bin
blocky                      github.com/0xERR0R/blocky

C
caddy                       github.com/caddyserver/caddy
caire                       github.com/esimov/caire
captainhook                 github.com/bketelsen/captainhook
```

***

**Step #­2:** Delete every blank line
```
/^$/d;
```
`/` = start pattern
`^` = match the start of a line (regex)
`$` = match the end of a line (regex)
`/` = end pattern
`d` = delete pattern
`;` = separator between `sed` steps

**Output**
```
A
acme-dns                    github.com/joohoi/acme-dns
adguardhome                 github.com/AdguardTeam/AdGuardHome
age                         github.com/FiloSottile/age
B
bed                         github.com/itchyny/bed
bin                         github.com/w4/bin
blocky                      github.com/0xERR0R/blocky
C
caddy                       github.com/caddyserver/caddy
caire                       github.com/esimov/caire
captainhook                 github.com/bketelsen/captainhook
```

***

**Step #­3:** Add `| ` ­ to the start of every line
```
s,^,| ,g;
```
`s` = replace pattern
`,` = start match pattern\*
`^` = match the start of a line (regex)
`,` = end match pattern, start replace pattern\*
`| ` ­ = replace with `| ` ­
`,` = end replace pattern\*
`g` = replace all matches, not just the first one
`;` = separator between `sed` steps

\*You would normally use `/` here, but `sed` is smart enough to accept (almost) any character that is used three times as a pattern separator.

**Output**
```
| A
| acme-dns                    github.com/joohoi/acme-dns
| adguardhome                 github.com/AdguardTeam/AdGuardHome
| age                         github.com/FiloSottile/age
| B
| bed                         github.com/itchyny/bed
| bin                         github.com/w4/bin
| blocky                      github.com/0xERR0R/blocky
| C
| caddy                       github.com/caddyserver/caddy
| caire                       github.com/esimov/caire
| captainhook                 github.com/bketelsen/captainhook
```

***

**Step #­4:** Delete all instances of `| A` through `| Z`
```
s,| [A-Z],,g;
```
`s` = replace pattern
`,` = start match pattern
`| ` ­ = match `| ` ­
`[A-Z]` = match all uppercase letters from A-Z (regex)
`,` = end match pattern, start replace pattern
`­` = nothing (i.e. delete the pattern)
`,` = end replace pattern
`g` = replace all matches, not just the first one
`;` = separator between `sed` commands

**Output**
```

| acme-dns                    github.com/joohoi/acme-dns
| adguardhome                 github.com/AdguardTeam/AdGuardHome
| age                         github.com/FiloSottile/age

| bed                         github.com/itchyny/bed
| bin                         github.com/w4/bin
| blocky                      github.com/0xERR0R/blocky

| caddy                       github.com/caddyserver/caddy
| caire                       github.com/esimov/caire
| captainhook                 github.com/bketelsen/captainhook
```

***

**Step #­5:** Delete every blank line (again)
```
/^$/d;
```
`/` = start pattern
`^` = match the start of a line (regex)
`$` = match the end of a line (regex)
`/` = end pattern
`d` = delete pattern
`;` = separator between `sed` steps

**Output**
```
| acme-dns                    github.com/joohoi/acme-dns
| adguardhome                 github.com/AdguardTeam/AdGuardHome
| age                         github.com/FiloSottile/age
| bed                         github.com/itchyny/bed
| bin                         github.com/w4/bin
| blocky                      github.com/0xERR0R/blocky
| caddy                       github.com/caddyserver/caddy
| caire                       github.com/esimov/caire
| captainhook                 github.com/bketelsen/captainhook
```

***

**Step #­6:** Replace `github.com` with `| https://github.com`
```
s,github.com,| https://github.com,g;
```
`s` = replace pattern
`,` = start match pattern
`github.com` ­ = match `github.com`
`,` = end match pattern, start replace pattern
`| https://github.com­` = replace with `| https://github.com`
`,` = end replace pattern
`g` = replace all matches, not just the first one
`;` = separator between `sed` commands

**Output**
```
| acme-dns                    | https://github.com/joohoi/acme-dns
| adguardhome                 | https://github.com/AdguardTeam/AdGuardHome
| age                         | https://github.com/FiloSottile/age
| bed                         | https://github.com/itchyny/bed
| bin                         | https://github.com/w4/bin
| blocky                      | https://github.com/0xERR0R/blocky
| caddy                       | https://github.com/caddyserver/caddy
| caire                       | https://github.com/esimov/caire
| captainhook                 | https://github.com/bketelsen/captainhook
```

***

**Step #­7:** Add `­ |` ­to the end of every line
```
s,$, |,g
```

`s` = replace pattern
`,` = start match pattern
`$` = match the end of a line (regex)
`,` = end match pattern, start replace pattern
`­ |` = replace with `­ |`
`,` = end replace pattern
`g` = replace all matches, not just the first one
`;` = separator between `sed` commands

**Output**
```
| acme-dns                    | https://github.com/joohoi/acme-dns |
| adguardhome                 | https://github.com/AdguardTeam/AdGuardHome |
| age                         | https://github.com/FiloSottile/age |
| bed                         | https://github.com/itchyny/bed |
| bin                         | https://github.com/w4/bin |
| blocky                      | https://github.com/0xERR0R/blocky |
| caddy                       | https://github.com/caddyserver/caddy |
| caire                       | https://github.com/esimov/caire |
| captainhook                 | https://github.com/bketelsen/captainhook |
```

***

And that's all there is to it. 😄

**Pull request closed without merging**
